<script type="text/javascript">
    jssor_1_slider_init = function () {

        var jssor_1_options = {
            $AutoPlay: 1,
            $SlideDuration: 800,
            $SlideEasing: $Jease$.$OutQuint,
            $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
            },
            $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$
            }
        };

        var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

        /*#region responsive code begin*/

        var MAX_WIDTH = 3000;

        function ScaleSlider() {
            var containerElement = jssor_1_slider.$Elmt.parentNode;
            var containerWidth = containerElement.clientWidth;

            if (containerWidth) {

                var expectedWidth = Math.min(MAX_WIDTH || containerWidth, containerWidth);

                jssor_1_slider.$ScaleWidth(expectedWidth);
            }
            else {
                window.setTimeout(ScaleSlider, 30);
            }
        }

        ScaleSlider();

        $Jssor$.$AddEvent(window, "load", ScaleSlider);
        $Jssor$.$AddEvent(window, "resize", ScaleSlider);
        $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
        /*#endregion responsive code end*/
    };
</script>
<section class="store-front">
    <div class="slider">
        <div id="jssor_1"
             style="position:relative;margin:0 auto;top:0px;left:0px;width:1300px;max-height:1070px; overflow:hidden;visibility:hidden;">
            <!-- Loading Screen -->
            <div data-u="loading" class="jssorl-009-spin"
                 style="position:absolute;top:0px;left:0px;width:100%;height:100%;text-align:center;background-color:rgba(0,0,0,0.7);">
                <img style="margin-top:-19px;position:relative;top:50%;width:38px;height:38px;"
                     src="<?php echo $this->getSkinUrl('images/spin.svg');?>"/>
            </div>
            <div data-u="slides"
                 style="cursor:default;position:relative;top:0px;left:0px;width:1300px;height:1070px;overflow:hidden;">
                <div class="slide1">
                    <img style="width:100%;" src="<?php echo $this->getSkinUrl('images/slides/slide1.png');?>" alt="">
                    <h1>DIGITAL STORE FRONT</h1>
                    <h6>ORDER, TRACK, GENERATE TEMPLATES & CREATE CUSTOM COLLATERAL</h6>
                    <button class="tg-button" type="button">Order</button>
                </div>
            </div>
            <!-- Bullet Navigator -->
            <div data-u="navigator" class="jssorb032" style="position:absolute;bottom:12px;right:12px;"
                 data-autocenter="1" data-scale="0.5" data-scale-bottom="0.75">
                <div data-u="prototype" class="i" style="width:16px;height:16px;">
                    <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">
                        <circle class="b" cx="8000" cy="8000" r="5800"></circle>
                    </svg>
                </div>
            </div>
            <!-- Arrow Navigator -->
<!--            <div data-u="arrowleft" class="jssora051" style="width:65px;height:65px;top:0px;left:25px;"-->
<!--                 data-autocenter="2" data-scale="0.75" data-scale-left="0.75">-->
<!--                <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">-->
<!--                    <polyline class="a" points="11040,1920 4960,8000 11040,14080 "></polyline>-->
<!--                </svg>-->
<!--            </div>-->
<!--            <div data-u="arrowright" class="jssora051" style="width:65px;height:65px;top:0px;right:25px;"-->
<!--                 data-autocenter="2" data-scale="0.75" data-scale-right="0.75">-->
<!--                <svg viewBox="0 0 16000 16000" style="position:absolute;top:0;left:0;width:100%;height:100%;">-->
<!--                    <polyline class="a" points="4960,1920 11040,8000 4960,14080 "></polyline>-->
<!--                </svg>-->
<!--            </div>-->
        </div>
    </div>
</section>
        <script type="text/javascript">jssor_1_slider_init();</script>