<section class="store-front">
    <div class="slider">
        <div class="row">
            <div class="large-12 columns">
                <div class="owl-carousel owl-theme">
                    <div class="item">
                        <div class="slide1">
                            <img data-u="image"
                                 src="<?php echo $this->getSkinUrl('images/slides/slide1.png'); ?>"/>
                            <div class="slide-content">
                                <h1>DIGITAL STORE FRONT</h1>
                                <h6>ORDER, TRACK, GENERATE TEMPLATES & CREATE CUSTOM COLLATERAL</h6>
                                <button class="tg-button" type="button">Order</button>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slide1">
                            <img data-u="image"
                                 src="<?php echo $this->getSkinUrl('images/slides/slide1.png'); ?>"/>
                            <div class="slide-content">
                                <h1>DIGITAL STORE FRONT</h1>
                                <h6>ORDER, TRACK, GENERATE TEMPLATES & CREATE CUSTOM COLLATERAL</h6>
                                <button class="tg-button" type="button">Order</button>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="slide1">
                            <img data-u="image"
                                 src="<?php echo $this->getSkinUrl('images/slides/slide1.png'); ?>"/>
                            <div class="slide-content">
                                <h1>DIGITAL STORE FRONT</h1>
                                <h6>ORDER, TRACK, GENERATE TEMPLATES & CREATE CUSTOM COLLATERAL</h6>
                                <button class="tg-button" type="button">Order</button>
                            </div>
                        </div>
                    </div>
                </div>
                <script>
                    jQuery(document).ready(function() {
                        jQuery('.owl-carousel').owlCarousel({
                            items: 1,
                            margin: 10,
                            autoHeight: true
                        });
                    })
                </script>
            </div>
        </div>
    </div>
</section>
