<section class="quick-turnaround">
    <div class="quick-turnaround-content">
        <div class="col-4">
            <div class="turn1">
                <div class="turn1-container">
                    <p class="red">
                        5 days
                    </p>
                    <p>turnaround for<br>
                        standard orders</p>
                </div>

            </div>
        </div>
        <div class="col-4">
            <div class="turn2">
                <div class="turn2-container">
                    <p class="red">
                        14 days
                    </p>
                    <p>turnaround for<br>
                        custom design<br>
                        orders</p>
                </div>

            </div>
        </div>
        <div class="col-4">
            <div class="turn3">
                <div class="turn3-container">
                    <p class="red">
                        Turn Around
                    </p>
                    <p>Is estimated with<br>
                        standard shipping.<br>
                        Orders are<br>
                        processed upon<br>
                        approval.</p>
                </div>

            </div>
        </div>
    </div>
</section>
<section class="printing-category">
    <div class="printing-category-top">
        <h2>PRINTING CATEGORY</h2>
        <p class="printing-category-top-desc">Order your print needs on the go. Most orders have 5 day turnaround<br>
            with standard shipping. Plan accordingly and make sure you don’t run out!</p>
        <div class="printing-category-top-circles mobile-hide">
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                <p>MENU</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                <p>SIGNAGE</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                <p>MARKETING &<br>
                    PROMOTION</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                <p>CATERING</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                <p>STATIONARY</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                <p>KIT</p>
            </div>
        </div>
        <div class="printing-category-top-circles-mob mobile-show">
            <div class="owl-carousel owl-theme">
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
            </div>
            <div class="printing-category-top-circles mobile-hide">
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                    <p>SIGNAGE</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                    <p>MARKETING &<br>
                        PROMOTION</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                    <p>CATERING</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                    <p>STATIONARY</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                    <p>KIT</p>
                </div>
            </div>
        </div>
    </div>
    <div class="printing-category-grid">
        <div class="printing-category-grid-container">
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid1.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-menu.png'); ?>"
                             alt="">
                        <p class="red">MENU</p>
                        <p class="descr">paper to-go menus &<br>
                            nutritional and allergen<br>
                            information cards</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-signage.png'); ?>"
                             alt="">
                        <p class="red">SIGNAGE</p>
                        <p class="descr">in store, food, drink signs, sign<br>
                            holders & wall menu boards</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid2.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid3.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 bg-aqua">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-marketing.png'); ?>"
                             alt="">
                        <p class="white">MARKETING &<br>
                            PROMOTION</p>
                        <p class="descr">coupons, kindness cards &<br>
                            event promotion collateral</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-yellow">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-catering.png'); ?>"
                             alt="">
                        <p class="cat">CATEGORY 4</p>
                        <p class="white">CATERING</p>
                        <p class="descr">catering sticker labels, tent cards,<br>
                            tape & additional print items</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid4.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid5.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-stationary.png'); ?>"
                             alt="">
                        <p class="cat">CATEGORY 5</p>
                        <p class="red">STATIONARY</p>
                        <p class="descr">business cards, buckslips &<br>
                            additional writing items</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-grey">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-kit.png'); ?>" alt="">
                        <p class="cat">CATEGORY 6</p>
                        <p class="red">KIT</p>
                        <p class="descr">catering stickers, catering<br>
                            tent cards, tapes & new<br>
                            store opening kits</p>
                        <button class="tg-more">more</button>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid6.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<section class="track_order">
    <div class="track_order_container">
        <h6>SHIPPING</h6>
        <h2>TRACK MY ORDER</h2>
        <p>Find My Order</p>
        <form class="order_number" name="order_number">
            <input type="" placeholder="Order #" name="order" autocomplete="off">
            <button type="button"><span>FIND</span></button>
        </form>
    </div>
    <div class="triangle">
        <i class="fas fa-chevron-down"></i>
    </div>
</section>
<section class="shipping-status">
    <div class="shipping-status-container">
        <h3>Your shipping status</h3>
        <div class="progress-bar-order progress-first-step mobile-hide">
            <div class="progress progress-striped">
                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0"
                     aria-valuemax="100">
                </div>
            </div>
            <div class="points-progress">
                <div class="progress-point ">
                    <h6>01</h6>
                    <div class="progress-point-circle">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <p class="current-step">Order is Ready</p>
                </div>
                <div class="progress-point">
                    <h6>02</h6>
                    <div class="progress-point-circle">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <p>Delivery Service</p>
                </div>
                <div class="progress-point">
                    <h6>03</h6>
                    <div class="progress-point-circle">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <p>Accepted by Courier</p>
                </div>
                <div class="progress-point">
                    <h6>04</h6>
                    <div class="progress-point-circle">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <p>Order Delivery </p>
                </div>
                <div class="progress-point">
                    <h6>05</h6>
                    <div class="progress-point-circle">
                        <i class="fas fa-check-tg"></i>
                    </div>
                    <p>Order Issued</p>
                </div>
            </div>
        </div>

        <div class="progress-bar-order-mobile mobile-show">
            <div id="progress-bar-mobile" class="progress-bar-mobile step2">
                <div class="progress-line">
                    <div class="pouring"></div>
                </div>
                <div class="progress-dots">
                    <div class="progress-col-4">
                        <div class="progress-dot progress-dot1"></div>
                    </div>
                    <div class="progress-col-4">
                        <div class="progress-dot progress-dot2"></div>
                    </div>
                    <div class="progress-col-4">
                        <div class="progress-dot progress-dot3"></div>
                    </div>
                </div>
                <div class="progress-steps">
                    <div class="progress-col-4">
                        <div class="progress-step progress-step1"><p>order placed</p></div>
                    </div>
                    <div class="progress-col-4">
                        <div class="progress-step progress-step2"><p>order processing</p></div>
                    </div>
                    <div class="progress-col-4">
                        <div class="progress-step progress-step3"><p>accepted by courier</p></div>
                    </div>
                </div>
            </div>
        </div>
        <button class="more-inf">More information</button>
    </div>
</section>

<section class="printing-demand">
    <div class="printing-demand-container">
        <h6>your design</h6>
        <h2>PRINTING <br>
            ON DEMAND</h2>
        <button class="tg-button" type="button">Create</button>

    </div>
</section>

<section class="order-request">
    <div class="order-request-container">
        <h6>order</h6>
        <h2>CUSTOM ORDER <br>
            REQUEST</h2>
        <button class="tg-button" type="button">Order</button>

    </div>
</section>
<section class="help-poc">
    <div class="help-poc-container">
        <h6>for client</h6>
        <h2>help-poc</h2>
        <p>Sing In</p>
        <form action="">
            <input class="help-poc-input" type="text" placeholder="E-mail" autocomplete="off">
            <input class="help-poc-input" type="text" placeholder="Password" autocomplete="off">
        </form>
        <button class="tg-button" type="button">login</button>
    </div>
</section>
<script>
    jQuery(document).ready(function () {
        jQuery('.owl-carousel').owlCarousel({
            items: 1,
            margin: 10,
            autoHeight: true
        });
    })
</script>