<section class="quick-turnaround">
    <h2>quick turnaround!</h2>

    <div class="quick-turnaround-content-mobile mobile-show">
        <div class="owl-carousel owl-theme">
            <div class="item">
                <div class="5days">
                    <div id="donut-container">
                        <div class="donut">
                            <span class="donut-count">5 days</span>
                            <div class="donut-center"></div>
                            <div class="donut-mask"></div>
                        </div>
                    </div>
                    <p>turnaround for <br>
                        standard orders</p>
                </div>
            </div>
            <div class="item">
                <div class="14days">
                    <div id="donut-container">
                        <div class="donut">
                            <span class="donut-count">14 days</span>
                            <div class="donut-center"></div>
                            <div class="donut-mask"></div>
                        </div>
                    </div>
                    <p>turnaround for custom<br>
                        design orders</p>
                </div>
            </div>
            <div class="item">
                <div class="turnaround-question">
                    <div id="donut-container">
                        <img class="img-turnaround-question"
                             src="<?php echo $this->getSkinUrl('images/faq-turnaround.png'); ?>"
                             alt="">
                    </div>
                    <p>Log in to acess the full site.<br>
                        Check out <strong>FAQ</strong> for more info</p>
                </div>
            </div>
        </div>
    </div>


    <div class="quick-turnaround-content mobile-hide">
        <div class="5days">
            <div id="donut-container">
                <div class="donut">
                    <span class="donut-count">5 days</span>
                    <div class="donut-center"></div>
                    <div class="donut-mask"></div>
                </div>
            </div>
            <p>turnaround for <br>
                standard orders</p>
        </div>
        <div class="14days">
            <div id="donut-container">
                <div class="donut">
                    <span class="donut-count">14 days</span>
                    <div class="donut-center"></div>
                    <div class="donut-mask"></div>
                </div>
            </div>
            <p>turnaround for custom<br>
                design orders</p>
        </div>
        <div class="turnaround-question">
            <div id="donut-container">
                <img class="img-turnaround-question" src="<?php echo $this->getSkinUrl('images/faq-turnaround.png'); ?>"
                     alt="">
            </div>
            <p>Log in to acess the full site.<br>
                Check out <strong>FAQ</strong> for more info</p>
        </div>
    </div>
    <span class="quick-turnaround-bottom-text">Estimated turnaround time is calculated with standard shipping. Orders are processed after approval.</span>
</section>
<section class="printing-category">
    <div class="printing-category-top">
        <h2>PRINTING CATEGORY</h2>
        <p class="printing-category-top-desc">Order your print needs on the go. Most orders have 5 day turnaround<br>
            with standard shipping. Plan accordingly and make sure you don’t run out!</p>
        <div class="printing-category-top-circles mobile-hide">
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                <p>MENU</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                <p>SIGNAGE</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                <p>MARKETING &<br>
                    PROMOTION</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                <p>CATERING</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                <p>STATIONARY</p>
            </div>
            <div>
                <img class="img-printing-category"
                     src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                <p>KIT</p>
            </div>
        </div>
        <div class="printing-category-top-circles-mob mobile-show">
            <div class="owl-carousel owl-theme">
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div class="item">
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
            </div>
            <div class="printing-category-top-circles mobile-hide">
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                    <p>MENU</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                    <p>SIGNAGE</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                    <p>MARKETING &<br>
                        PROMOTION</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                    <p>CATERING</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                    <p>STATIONARY</p>
                </div>
                <div>
                    <img class="img-printing-category"
                         src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                    <p>KIT</p>
                </div>
            </div>
        </div>
    </div>
    <div class="printing-category-grid">
        <div class="printing-category-grid-container">
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid1.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-menu.png'); ?>"
                             alt="">
                        <p class="red">MENU</p>
                        <p class="descr">paper to-go menus &<br>
                            nutritional and allergen<br>
                            information cards</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-signage.png'); ?>"
                             alt="">
                        <p class="red">SIGNAGE</p>
                        <p class="descr">in store, food, drink signs, sign<br>
                            holders & wall menu boards</p>
                    </div>
                </div>
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid2.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid3.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 bg-aqua">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-marketing.png'); ?>"
                             alt="">
                        <p class="white">MARKETING &<br>
                            PROMOTION</p>
                        <p class="descr">coupons, kindness cards &<br>
                            event promotion collateral</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-yellow">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-catering.png'); ?>"
                             alt="">
                        <p class="cat">CATEGORY 4</p>
                        <p class="white">CATERING</p>
                        <p class="descr">catering sticker labels, tent cards,<br>
                            tape & additional print items</p>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid4.png'); ?>" alt="">
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid5.png'); ?>" alt="">
                </div>
                <div class="col-6 col-small-12 brd-r-l">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-stationary.png'); ?>"
                             alt="">
                        <p class="cat">CATEGORY 5</p>
                        <p class="red">STATIONARY</p>
                        <p class="descr">business cards, buckslips &<br>
                            additional writing items</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-small-12 bg-grey">
                    <div class="printing-category-grid-content">
                        <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-kit.png'); ?>" alt="">
                        <p class="cat">CATEGORY 6</p>
                        <p class="red">KIT</p>
                        <p class="descr">catering stickers, catering<br>
                            tent cards, tapes & new<br>
                            store opening kits</p>
                    </div>
                </div>
                <div class="col-6 col-small-12 right">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid6.png'); ?>" alt="">
                </div>
            </div>
        </div>
    </div>
</section>
<section class="track_order">
    <div class="track_order_container">
        <h2>TRACK MY ORDER / SHIPPING</h2>
        <form class="order_number" name="order_number">
            <input type="" placeholder="Enter your order number" name="order">
            <button type="button"><span>FIND</span></button>
        </form>
        <div class="progress-bar-order mobile-hide">
            <div class="progress progress-striped">
                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0"
                     aria-valuemax="100" style="width: 20%">
                </div>
            </div>
            <div class="points-progress">
                <div class="progress-point ">
                    <p class="current-step">order placed</p>
                </div>
                <div class="progress-point">
                    <p>order<br> processing</p>
                </div>
                <div class="progress-point">
                    <p>accepted<br>
                        by courier</p>
                </div>
                <div class="progress-point">
                    <p>out for<br>
                        delivery</p>
                </div>
                <div class="progress-point">
                    <p>delivered</p>
                </div>
            </div>
        </div>
    </div>
    <div class="progress-bar-order-mobile mobile-show">
        <div id="progress-bar-mobile" class="progress-bar-mobile step2">
            <div class="progress-line">
                <div class="pouring"></div>
            </div>
            <div class="progress-dots">
                <div class="progress-dot progress-dot1"></div>
                <div class="progress-dot progress-dot2"></div>
                <div class="progress-dot progress-dot3"></div>
            </div>
            <div class="progress-steps">
                <div class="progress-step progress-step1"><p>order placed</p></div>
                <div class="progress-step progress-step2"><p>order processing</p></div>
                <div class="progress-step progress-step3"><p>accepted by courier</p></div>
            </div>
        </div>
    </div>
</section>
<section class="order-request">
    <div class="order-request-container">
        <h2>CUSTOM ORDER REQUEST</h2>
        <p>
            Do you have something special in mind? Tell us what you <br>think and we’ll make you something cool!
        </p>
        <button class="tg-button" type="button">Order</button>

    </div>
</section>
<section class="template-generator">
    <div class="template-generator-container">
        <h2>TEMPLATE GENERATOR</h2>
        <p>
            Create daily special sheet, retail labels, and door signs.<br>
            Customize event posters and postcards.
        </p>
        <button class="tg-button" type="button">Create</button>

    </div>
</section>
<section class="need-help">
    <div class="need-help-container">
        <h2>NEED HELP?</h2>
        <p>Can’t find what you are looking for? Log in first to<br>
            access the complete site & functions. Check out <a class="need-help-faq" href="">FAQ</a> for more info.</p>
        <div class="row need-help-circles">
            <div class="col-6 col-small-12">
                <div class="aqua-circle">
                    <span class="tech-supp">technical<br>support</span>
                </div>
                <span class="black-font">SCG  Linda Gaeta</span>
                <p>linda_g@socalgraph.com<br>
                    310 863 1770</p>
            </div>
            <div class=" separate"></div>
            <div class="col-6 col-small-12">
                <div class="aqua-circle">
                    <span class="tech-supp">additional<br>questions</span>
                </div>
                <span class="black-font">TG Graphics</span>
                <p>graphics@tendergreens.com</p>
            </div>
        </div>
    </div>
</section>
<script>
    jQuery(document).ready(function () {
        jQuery('.owl-carousel').owlCarousel({
            items: 1,
            margin: 10,
            autoHeight: true
        });
    })
</script>