<section class="quick-turnaround">
    <h2>quick turnaround!</h2>
    <div class="quick-turnaround-content">
        <div class="5days">
            <div id="donut-container">
                <div class="donut donut--25">
                    <span class="donut-count">5 days</span>
                    <div class="donut-center"></div>
                    <div class="donut-mask"></div>
                </div>
            </div>
            <p>turnaround for <br>
                standard orders</p>
        </div>
        <div class="14days">
            <div id="donut-container">
                <div class="donut donut--48">
                    <span class="donut-count">14 days</span>
                    <div class="donut-center"></div>
                    <div class="donut-mask"></div>
                </div>
            </div>
            <p>turnaround for custom<br>
                design orders</p>
        </div>
        <div class="turnaround-question">
            <div id="donut-container">
                <img class="img-turnaround-question" src="<?php echo $this->getSkinUrl('images/faq-turnaround.png'); ?>"
                     alt="">
            </div>
            <p>Log in to acess the full site.<br>
                Check out <strong>FAQ</strong> for more info</p>
        </div>
    </div>
    <span class="quick-turnaround-bottom-text">Estimated turnaround time is calculated with standard shipping. Orders are processed after approval.</span>
</section>
<section class="printing-category">
    <div class="printing-category-top">
        <h2>PRINTING CATEGORY</h2>
        <p>Order your print needs on the go. Most orders have 5 day turnaround<br>
            with standard shipping. Plan accordingly and make sure you don’t run out!</p>
        <div class="printing-category-top-circles">
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category1.png'); ?>" alt="">
                <p>MENU</p>
            </div>
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category2.png'); ?>" alt="">
                <p>SIGNAGE</p>
            </div>
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category3.png'); ?>" alt="">
                <p>MARKETING &<br>
                    PROMOTION</p>
            </div>
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category4.png'); ?>" alt="">
                <p>CATERING</p>
            </div>
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category5.png'); ?>" alt="">
                <p>STATIONARY</p>
            </div>
            <div>
                <img class="img-printing-category" src="<?php echo $this->getSkinUrl('images/printing-category6.png'); ?>" alt="">
                <p>KIT</p>
            </div>
        </div>
    </div>
    <div class="printing-category-grid">
        <div class="printing-category-grid-container">
        <div class="row">
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid1.png'); ?>" alt="">
            </div>
            <div class="col-6">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-menu.png'); ?>" alt="">
                    <p class="red">MENU</p>
                    <p class="descr">paper to-go menus &<br>
                        nutritional and allergen<br>
                        information cards</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-signage.png'); ?>" alt="">
                    <p class="red">SIGNAGE</p>
                    <p class="descr">in store, food, drink signs, sign<br>
                        holders & wall menu boards</p>
                </div>
            </div>
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid2.png'); ?>" alt="">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid3.png'); ?>" alt="">
            </div>
            <div class="col-6 bg-aqua">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-marketing.png'); ?>" alt="">
                    <p class="white">MARKETING &<br>
                        PROMOTION</p>
                    <p class="descr">coupons, kindness cards &<br>
                        event promotion collateral</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6 bg-yellow">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-catering.png'); ?>" alt="">
                    <p class="cat">CATEGORY 4</p>
                    <p class="white">CATERING</p>
                    <p class="descr">catering sticker labels, tent cards,<br>
                        tape & additional print items</p>
                </div>
            </div>
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid4.png'); ?>" alt="">
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid5.png'); ?>" alt="">
            </div>
            <div class="col-6">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-stationary.png'); ?>" alt="">
                    <p class="cat">CATEGORY 5</p>
                    <p class="red">STATIONARY</p>
                    <p class="descr">business cards, buckslips &<br>
                        additional writing items</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-6 bg-grey">
                <div class="printing-category-grid-content">
                    <img src="<?php echo $this->getSkinUrl('images/printing-category-grid-kit.png'); ?>" alt="">
                    <p class="cat">CATEGORY 6</p>
                    <p class="red">KIT</p>
                    <p class="descr">catering stickers, catering<br>
                        tent cards, tapes & new<br>
                        store opening kits</p>
                </div>
            </div>
            <div class="col-6">
                <img src="<?php echo $this->getSkinUrl('images/printing-category-grid6.png'); ?>" alt="">
            </div>
        </div>
    </div>
    </div>
</section>
<section>
    <div style="display: inline-block; width: 100%;">111111111111111</div>
</section>
