<div class="footer">
    <div class="footer-links">
        <a href="#">TG web</a> // <a href="#">dashboard</a> // <a href="#">FAQ</a> // <a href="#">contact</a>
    </div>
    <div class="social-links">
        <a href="#"><img src="<?php echo $this->getSkinUrl('images/twit-ico.png'); ?>" alt=""></a>
        <a href="#"><img src="<?php echo $this->getSkinUrl('images/insta-ico.png'); ?>" alt=""></a>
        <a href="#"><img src="<?php echo $this->getSkinUrl('images/facebook-ico.png'); ?>" alt=""></a>
        <a href="#"><img src="<?php echo $this->getSkinUrl('images/youtube-ico.png'); ?>" alt=""></a>
    </div>
    <address class="copyright"><?php echo $this->getCopyright() ?></address>
</div>